{{cookiecutter.directory_name}}/djangobaseproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webpage.urls', namespace='webpage')),
    path('infos/', include('infos.urls', namespace='infos'))
]

handler404 = 'webpage.views.handler404'

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.urls import get_resolver

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    print(get_resolver().url_patterns)

{{cookiecutter.directory_name}}/infos/urls.py
from django.urls import path
from . import views
from . import special_views

app_name = 'infos'
urlpatterns = [
    path(
        'project-team',
        special_views.TeamView.as_view(),
        name='project-team'
    ),
    path(
        'about-the-project',
        special_views.SpecialAboutView.as_view(),
        name='about-the-project'
    ),
    path(
        'about',
        views.AboutTheProjectListView.as_view(),
        name='about_browse'
    ),
    path(
        'about/detail/<int:pk>',
        views.AboutTheProjectDetailView.as_view(),
        name='about_detail'
    ),
    path(
        'about/create',
        views.AboutTheProjectCreate.as_view(),
        name='about_create'
    ),
    path(
        'about/edit/<int:pk>',
        views.AboutTheProjectUpdate.as_view(),
        name='about_edit'
    ),
    path(
        'about/delete/<int:pk>',
        views.AboutTheProjectDelete.as_view(),
        name='about_delete'),
    path(
        'teammember',
        views.TeamMemberListView.as_view(),
        name='teammember_browse'
    ),
    path(
        'teammember/detail/<int:pk>',
        views.TeamMemberDetailView.as_view(),
        name='teammember_detail'
    ),
    path(
        'teammember/create',
        views.TeamMemberCreate.as_view(),
        name='teammember_create'
    ),
    path(
        'teammember/edit/<int:pk>',
        views.TeamMemberUpdate.as_view(),
        name='teammember_edit'
    ),
    path(
        'teammember/delete/<int:pk>',
        views.TeamMemberDelete.as_view(),
        name='teammember_delete'),
    path(
        'projectinst',
        views.ProjectInstListView.as_view(),
        name='projectinst_browse'
    ),
    path(
        'projectinst/detail/<int:pk>',
        views.ProjectInstDetailView.as_view(),
        name='projectinst_detail'
    ),
    path(
        'projectinst/create',
        views.ProjectInstCreate.as_view(),
        name='projectinst_create'
    ),
    path(
        'projectinst/edit/<int:pk>',
        views.ProjectInstUpdate.as_view(),
        name='projectinst_edit'
    ),
    path(
        'projectinst/delete/<int:pk>',
        views.ProjectInstDelete.as_view(),
        name='projectinst_delete'),
]

{{cookiecutter.directory_name}}/webpage/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django_spaghetti.views import Plate
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('imprint', views.ImprintView.as_view(), name="imprint"),
    path('', views.GenericWebpageView.as_view(), name="start"),
    path(
        'data-model',
        Plate.as_view(
            plate_template_name="webpage/data_model.html"
        ),
        name="data_model"
    ),
    path('accounts/login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('project-info/', views.project_info, name='project_info'),
    path('<slug:template>', views.GenericWebpageView.as_view(), name='staticpage'),
]

{{cookiecutter.directory_name}}/webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

{{cookiecutter.directory_name}}/webpage/views.py
from copy import deepcopy

import requests

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.template.exceptions import TemplateDoesNotExist
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout

from . forms import form_user_login
from . metadata import PROJECT_METADATA as PM


def get_imprint_url():
    try:
        base_url = settings.IMPRINT_URL
    except AttributeError:
        base_url = "https://provide-an-mdw-imprint-url/"
    return "{}".format(base_url)


class ImprintView(TemplateView):
    template_name = 'webpage/imprint.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imprint_url = get_imprint_url()
        r = requests.get(imprint_url)

        if r.status_code == 200:
            context['imprint_body'] = "{}".format(r.text)
        else:
            context['imprint_body'] = """
            On of our services is currently not available.\
            Please try it later or write an email to\
            repo-admin@mdw.ac.at; if you are service provide,\
            make sure that you provided ACDH_IMPRINT_URL and REDMINE_ID
            """
        return context


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(
            self.kwargs.get("template", 'index')
        )
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(
                self.kwargs.get("template", 'index')
            )
        except TemplateDoesNotExist:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render(request, "webpage/user_logout.html")


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)

    if request.user.is_authenticated:
        pass
    else:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

{{cookiecutter.directory_name}}/webpage/templates/webpage/404-error.html
{% extends "webpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
<div style="text-align: center;">
    
    <h2>We're sorry, the page you requested cannot be found.</h2>
    <p style="text-align: center">The page you're trying to access may not exist anymore or may have been moved. Try accessing it again from our site's homepage. Please also make sure that your spelling is correct.</p>
    <p style="text-align: center">If the problem persists, please report it as an issue <a href="https://gitlab.com/mdwrepository/djangobase-cookiecutter/issues">here</a>. Thank you!</p>

</div>
</div>
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">{% projects_metadata 'title' %}</h1>
        </div>
        <div class="card-body">
            <div>
                <p>
                    {% projects_metadata 'description' %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load static i18n %}
{% load webpage_extras %}
{% load browsing_extras %}
{% load infos_extras %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html class="no-js" lang="{{ LANGUAGE_CODE }}" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    {% block og_base %}
        <meta property="og:title" content="{% projects_metadata 'title' %}" />
        <meta property="og:description" content="{{ metadata.description }}" />
        <meta property="og:site_name" content="{% block og_site_name %}{{ self.get_site.site_name }}{% endblock %}"/>
        <meta property="og:type" content="{% block og_type %}website{% endblock %}"/>
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% settings_value 'SHARED_URL' %}/favicon/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% settings_value 'SHARED_URL' %}/favicon/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% settings_value 'SHARED_URL' %}/favicon/favicon-16x16.png"/>
        <link rel="manifest" href="{% settings_value 'SHARED_URL' %}/favicon/manifest.json"/>
        <link rel="manifest" href="{% settings_value 'SHARED_URL' %}/favicon/site.webmanifest"/>
        <link rel="mask-icon" href="{% settings_value 'SHARED_URL' %}/favicon/safari-pinned-tab.svg" color="#003b79"/>
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
    <!--favicons end -->
    <script src="{% settings_value 'SHARED_URL' %}shared/libraries/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/bootstrap-select/1.13.1/css/bootstrap-select.min.css" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" />
    <link rel="stylesheet" id="fundament-styles"  href="{% settings_value 'SHARED_URL' %}shared/libraries/fundament/css/fundament.min.css" type="text/css" />
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/bootstrap/4.3.1/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/font-awesome/6.1.1/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/select2/4.0.13/css/select2.min.css" type="text/css" />
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/select2-bootstrap4-theme/select2-bootstrap4.min.css" type="text/css" />
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% settings_value 'SHARED_URL' %}shared/libraries/scroll-to-top/css/ap-scroll-top.min.css" type="text/css" />
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% projects_metadata 'imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script src="{% static 'webpage/libraries/cookieconsent2/1.0.9/cookieconsent.min.js' %}" type="text/javascript"></script>
    <!-- End Cookie Consent plugin -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="home contained fixed-nav" id="body">
<a href="#main" name="main_content" id="main_content" tabindex="-1" class="sr-only">skip to main content</a>
<a href="#navigation" name="main_navivation" id="main_navigation" tabindex="-1" class="sr-only">skip to navigation</a>
<div class="hfeed site" id="page">
    <!-- blue mdw header bar -->
    <header>
        <div class="container header-firstRow">
            <div>
                <ul class="header-flexBox">
                    <li class="left mdwRepository">
                        <a href="https://repo.mdw.ac.at/" hreflang="{{ LANGUAGE_CODE }}" title="{% translate 'go to the homepage of the mdwRepository' %}"> mdwRepository </a>
                        <span class="sr-only"> {%  translate 'this link will forward to the mdwRepository homepage' %} </span>
                    </li>
                    <li class="mdwLogo">
                        <a href="https://mdw.ac.at/" aria-label="mdw website" title="zur Homepage der mdw" hreflang="{{ LANGUAGE_CODE }}">
                            <div class="svgLogo"></div>
                        </a>
                        <span class="sr-only"> {%  translate 'go to the homepage of the mdw' %} </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container header-secondRow">
            <div>
                <ul class="header-flexBox">
                    <li class="left appname">
                        <!-- change to project title abbreviation if needed  -->
                        <a href="{% if not SCRIPT_NAME == '' %}{{ SCRIPT_NAME }}{% endif %}/" aria-label="{%  translate 'go to the homepage' %}" title="{%  translate 'go to the homepage of ' %} {% projects_metadata 'title' %}" hreflang="{{ LANGUAGE_CODE }}"> {% projects_metadata 'title' %} </a>
                    </li>
                    <li class="right">
                        <!-- <span class="text-white">Quicklinks</span> -->
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <!-- blue mdw header bar -->
    <!-- navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="main_navivation">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                <!-- Your menu goes here -->
                <ul id="main-menu" class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'infos:about-the-project' %}">About the project</a>
                            <a class="dropdown-item" href="{% url 'infos:project-team' %}">Team</a>
                            <a class="dropdown-item" href="{% url 'webpage:data_model' %}">Data Model</a>
                            <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint | Impressum</a>
                        </div>
                    </li> {% if 'vocabs' in APPS %} {% if user.is_authenticated %} <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vocabs Curation <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu"> {% nav_menu app='vocabs' as links %} {% for x in links %} <a class="dropdown-item" href="{{ x.link }}">{{ x.name }}</a> {% endfor %} <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'api-root' %}">Export SKOS (API)</a>
                        </div>
                    </li> {% endif %} {% endif %}
                </ul>
                <ul class="navbar-nav justify-content-end"> {% if user.is_authenticated %} <li class="nav-item dropdown ml-auto">
                        <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="nav-link" href="{% url 'webpage:user_logout' %}">log out <i class="feather-32" data-feather="log-out"></i></a>
                        </div>
                    </li> {% else %} <li class="nav-item dropdown my-2 my-lg-0">
                        <a class="nav-link" href="{% url 'webpage:user_login' %}">
                            <i class="feather-32" data-feather="log-in"></i>
                        </a>
                    </li> {% endif %} </ul>
            </div>
            <!-- .collapse navbar-collapse -->
        </div>
        <!-- .container -->
    </nav>
    <!-- .site-navigation -->
    <!-- main content -->
    <main>
        <div id="content" class="container">
            <div id="mainContent" class="mainContent doppel clearfix">
                {% if DEV_VERSION %}
                    <div class="alert alert-danger" role="alert">
                        This is a DEVELOPMENT instance. Click <a href="https://repo.mdw.ac.at/{{ PROJECT_NAME }}">here</a> for the Production version
                    </div>
                {% endif %}
                {# Main content of page - other layout templates override this block #}
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    <footer>
        <div class="container mainfooter">
            ©&nbsp;{% now 'Y' %}&nbsp;mdw – Universität für Musik und darstellende Kunst Wien<br/>
            &nbsp; Anton-von-Webern-Platz1, 1030 Wien, T +43 1 711 55<br/>
            <a href="{% url 'webpage:staticpage' template='imprint' %}" title="{%  translate 'imprint of the mdwRepository' %}"
            aria-label="{%  translate 'imprint' %}" alt="{%  translate 'imprint of the mdwRepository' %}">
                {%  translate 'imprint' %}
            </a>
            |
            <a href="https://www.mdw.ac.at/datenschutz/?PageId=6" target="_blank" aria-label="{%  translate 'data protection' %}"
               alt="{%  translate 'data protection information of the mdw' %}">
                {%  translate 'data protection' %} <span class="sr-only">opens in a new window</span>
            </a>
            |
            <a href="https://www.mdw.ac.at/repository/terms-of-use/" target="_blank" aria-label="{%  translate 'terms of use' %}"
               alt="{%  translate 'terms of use of the mdwRepository' %}">
                {%  translate 'terms of use' %}  <span class="sr-only">opens in a new window</span>
            </a>
            {% if user.is_authenticated %}
                {% if DB_NAME %}
                       <small>{{ DB_NAME }}</small>
                 {% endif %}
            {% endif %}
        </div>
    </footer>
</div>
        {% block scripts %}
            <script src="{% settings_value 'SHARED_URL' %}shared/libraries/fundament/js/fundament.min.js" type="text/javascript"></script>
            <script src="{% settings_value 'SHARED_URL' %}shared/libraries/popper.js/1.14.7/umd/popper.min.js" type="text/javascript"></script>
            <script src="{% settings_value 'SHARED_URL' %}shared/libraries/bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
            <script src="{% settings_value 'SHARED_URL' %}shared/libraries/bootstrap-select/1.13.1/js/bootstrap-select.min.js" type="text/javascript"></script>
            <script src="{% settings_value 'SHARED_URL' %}shared/libraries/scroll-to-top/js/ap-scroll-top.min.js" type="text/javascript"></script>     {% endblock %}
        {% block scripts2 %}
        {% endblock scripts2 %}
    </body>
</html>

{{cookiecutter.directory_name}}/webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/data_model.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Datenmodell {% endblock %}
{% block content %}
<div class="container">
    <style>
        #visualization {
            height: 800px;
        }
    </style>
    {% include 'django_spaghetti/plate.html' %}
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Imprint {% endblock %}
{% block content %}
<div class="container">
<div class="card imprint">
<div class="card-body">
    {{ imprint_body|safe }}
</div>
</div>
</div>
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load static %}
{% load stats_extras %}
{% load webpage_extras %}
{% block content %}

        <div class="jumbotron" style="background-image: url({% static 'webpage/img/project_background.jpg' %}) ">
            <div class="container">
                <h1 style="text-align:center; color: #111;">{% projects_metadata 'title' %}</h1>
                <h3 style="text-align:center; color: #111;">{% projects_metadata 'subtitle' %}</h3>
                <h5 style="text-align:center; color: #111;">{% projects_metadata 'description' %}</h5>
            </div>
        </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align:center">
                <h4>Data-Count</h4>
            </div>
            {% create_object_count app='vocabs' as models %}
            {% for x in models %}
                <div class="col-md-4  text-center">
                    <div class="card flex-md-row mb-4 box-shadow">
                        <div class="card-body">
                            <h4 class="mb-0">{{x.name}}</h4>
                            <h4 class="count">{{ x.count }}</h4>
                            {% if x.link %}
                                <a class="btn btn-main btn-outline-primary btn-sm" href="{{ x.link }}" role="button">View Details</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}

{{cookiecutter.directory_name}}/webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Logout {% endblock %}
{% block content %}
<div class="jumbotron container">
    <h1>Sayōnara!</h1>
    <p>You've signed out</p>
</div>
{% endblock content %}